### ISSUE TITLE
SendBirdUIKi' was built without full bitcode

### ISSUE THREAD

**Issue by minon250** [sendbird/UIKit-iOS-Swift#1]
When I try to achieve the project for release I get the following error. 
**ld: bitcode bundle could not be generated because '/Users/minon/Desktop/voh-ios/VoiceOfHealth/Pods/SendBirdUIKit/SendBirdUIKit.framework/SendBirdUIKit' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/minon/Desktop/voh-ios/VoiceOfHealth/Pods/SendBirdUIKit/SendBirdUIKit.framework/SendBirdUIKit' for architecture arm64**

**Comment by tezpark** [comment]
Thank you for reporting the issue.
We just released a new version of Bitcode support. Please try again using version 1.0.1.
